name: build

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  update_erd:
    name: update_erd
    runs-on: ubuntu-latest
    env:
      CONFLUENCE_PAGE_ID: ${{ secrets.CONFLUENCE_STAGING_PAGE_ID }}
      CONFLUENCE_USER: ${{ secrets.CONFLUENCE_USER }}
      CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
      REDIS_URL: redis://127.0.0.1:6379/0
      PUBLIC_URL: http://fake-cosmos-public-url
      TESTING: "True"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: sudo apt-get install graphviz graphviz-dev
      - run: pip install poetry
      - run: poetry config virtualenvs.create false
      - run: poetry config http-basic.azure jeff ${{secrets.AZURE_DEVOPS_PAT}}
      - run: poetry install --with erd
      - run: python scripts/erd/generate_upload_erd.py --update --schema-env=Staging  --version=${{ github.ref_name }} --message="Auto-update by Cosmos CI run number - ${{ github.run_number }}"
  build:
    uses: binkhq/actions/.github/workflows/python_build.yaml@master
    with:
      python_version: "3.11"
      application_name: ${{ github.event.repository.name }}
      application_version: ${{ github.ref_name }}
    secrets: inherit
  release:
    needs: ["build"]
    uses: binkhq/actions/.github/workflows/python_release.yaml@master
    with:
      source: ${{ github.event.repository.name }}:${{ github.ref_name }}
      tags: ${{ matrix.environment }}-${{ github.ref_name }},${{ matrix.environment }}
      environment:  ${{ matrix.environment }}
    secrets: inherit
    strategy:
      matrix:
        environment: [staging, production]
