on:
  workflow_call:
    inputs:
      schema-env:
        required: true
        type: string
    secrets:
      CONFLUENCE_PAGE_ID:
        required: true
      CONFLUENCE_USER:
        required: true
      CONFLUENCE_API_TOKEN:
        required: true

jobs:
  update_erd:
    name: update_erd
    runs-on: ubuntu-latest
    env:
      CONFLUENCE_PAGE_ID: ${{ secrets.CONFLUENCE_PAGE_ID }}
      CONFLUENCE_USER: ${{ secrets.CONFLUENCE_USER }}
      CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
      REDIS_URL: redis://127.0.0.1:6379/0
      PUBLIC_URL: http://fake-cosmos-public-url
      TESTING: "True"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: sudo apt-get install graphviz graphviz-dev
      - run: pip install poetry
      - run: poetry config virtualenvs.create false
      - run: poetry config http-basic.bink-pypi 269fdc63-af3d-4eca-8101-8bddc22d6f14 b694b5b1-f97e-49e4-959e-f3c202e3ab91
      - run: poetry install --with erd
      - run: python scripts/erd/generate_upload_erd.py --update --schema-env=${{ inputs.schema-env }}  --version=${{ github.ref_name }} --message='Auto-update by Cosmos CI run number - ${{ github.run_number }}'